dist: bionic
language: rust
services: docker
sudo: required

rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

before_install:
  - set -e
  - rustup self update

install:
  - cargo install --force just
  - rustup component add rustfmt || true
  - rustup component add clippy || true
  - source ~/.cargo/env || true

script:
  - just test
  - just check

after_script: set +e

cache: cargo
before_cache:
  - chmod -R a+r $HOME/.cargo

notifications:
  email:
    on_success: never
